export const TYPE_COLORS = {
  none: '#ccc',
  normal: '#A8A878',
  flying: '#A890F0',
  poison: '#A040A0',
  ghost: '#705898',
  psychic: '#F85888',
  water: '#6890F0',
  ice: '#98D8D8',
  dragon: '#7038F8',
  dark: '#7d7874',
  rock: '#B8A038',
  electric: '#dcbb38',
  ground: '#E0C068',
  fighting: '#C03028',
  bug: '#A8B820',
  steel: '#B8B8D0',
  fire: '#F08030',
  grass: '#78C850',
  fairy: '#EE99AC',
};

export const TYPE_ICONS = {
  none: 'fa-question',
  normal: 'fa-circle',
  flying: 'fa-feather-alt',
  poison: 'fa-skull',
  ghost: 'fa-ghost',
  psychic: 'fa-eye',
  water: 'fa-water',
  ice: 'fa-snowflake',
  dragon: 'fa-dragon',
  dark: 'fa-moon',
  rock: 'fa-gem',
  electric: 'fa-bolt',
  ground: 'fa-mountain',
  fighting: 'fa-fist-raised',
  bug: 'fa-bug',
  steel: 'fa-cog',
  fire: 'fa-fire',
  grass: 'fa-leaf',
  fairy: 'fa-bahai',
};